query Homepage {
	homepage {
		slider_collection {
			title
			big_title
			image {
				id
			}
		}
		position
		look_image {
			id
		}
		look_product {
			products_id {
				id
				slug
				title
				main_image {
					id
				}
				product_variants {
					price
				}
			}
		}
		uniq_product_image {
			id
		}
		uniq_product_image_2 {
			id
		}
		uniq_product_id {
			id
			slug
		}
	}
	homepage_products {
		products_id {
			id
			slug
			title
			main_image {
				id
			}
			product_variants {
				price
			}
		}
	}
	homepage_banners_1 {
		title
		image {
			id
		}
		collection
		item {
			... on collection {
				title
				id
			}
			... on categories {
				title
				id
			}
		}
	}
}
