query Products(
	$limit: Int
	$sort: [String]
	$page: Int
	$filter: products_filter
) {
	products(filter: $filter, sort: $sort, limit: $limit, page: $page) {
		id
		slug
		title
		main_image {
			id
		}
		product_variants {
			id
			price
			image {
				id
			}
		}
	}
	products_aggregated(filter: $filter) {
		count {
			id
		}
	}
}

query GetProductsByIds($ids: [String]) {
	products(filter: {id: {_in: $ids}}) {
		id
		slug
		main_image {
			id
		}
		title
		product_variants {
			id
			price
			color_id {
				title
			}
			size_id {
				small_title
			}
			image {
				id
			}
			qunatity
		}
	}
}

query GetCartProductsByIds($ids: [String], $variant_ids: [String]) {
	products(filter: {id: {_in: $ids}}) {
		id
		slug
		main_image {
			id
		}
		title
		product_variants(filter: {id: {_in: $variant_ids}}) {
			id
			color_id {
				title
			}
			size_id {
				small_title
			}
			image {
				id
			}
			price
			qunatity
		}
	}
}

query GetRandomProducts($id: String) {
	products(filter: {id: {_neq: $id}}, limit: 4) {
		id
		slug
		title
		product_variants {
			price
		}
		main_image {
			id
		}
	}
}

query SearchProducts($title: String) {
	products(search: $title) {
		id
		slug
		title
		main_image {
			id
		}
		product_variants {
			price
		}
	}
}
