query Catalog {
	catalog {
		SEO {
			meta_title
			meta_description
			og_image {
				id
			}
		}
		main_banner {
			id
		}
		main_banner_collection {
			title
		}
		random_banners {
			directus_files_id {
				id
			}
		}
		random_banners_collection {
			collection_id {
				title
			}
			image {
				id
			}
		}
	}
	products_aggregated {
		count {
			id
		}
		min {
			price
		}
		max {
			price
		}
	}
	brands {
		title
		description
		id
	}
	colors {
		title
		id
	}
	sizes {
		small_title
		large_title
		id
	}
	collection {
		title
		id
	}
}
