query Catalog {
	catalog {
		SEO {
			meta_title
			meta_description
			og_image {
				id
			}
		}
		main_banner {
			id
		}
		main_banner_collection {
			title
		}
		random_banners_collection {
			collection_id {
				title
			}
			image {
				id
			}
		}
	}
	products_aggregated {
		count {
			id
		}
	}
	product_variants_aggregated {
		min {
			price
		}
		max {
			price
		}
	}
	brands(filter: {status: {_eq: "published"}}) {
		title
		description
		id
	}
	colors(filter: {status: {_eq: "published"}}) {
		title
		id
	}
	sizes(filter: {status: {_eq: "published"}}) {
		small_title
		large_title
		id
	}
	collection(filter: {status: {_eq: "published"}}) {
		title
		id
	}
	categories(filter: {status: {_eq: "published"}}) {
		title
		id
	}
}
