query GetProductById($id: ID!) {
	products_by_id(id: $id) {
		id
		title
		description
		product_variants {
			color_id {
				title
			}
			size_id {
				small_title
			}
			qunatity
		}
		main_image {
			id
		}
		category {
			title
		}
		colors {
			colors_id {
				title
				id
			}
		}
		sizes {
			sizes_id {
				small_title
				id
			}
		}
		price
	}
}
