query GlobalConfig {
	site {
		seo {
			meta_title
			og_image {
				id
			}
			meta_description
		}
		general_message
		current_phone_number
		current_address
		current_email
		current_whatsapp
	}
}
