query Homepage {
	homepage {
		slider_collection {
			title
			big_title
			image {
				id
			}
		}
		look_image {
			id
		}
		look_product {
			products_id {
				id
				title
				price
				main_image {
					id
				}
			}
		}
		uniq_product_image {
			id
		}
		uniq_product_image_2 {
			id
		}
		uniq_product_id {
			id
		}
	}
	homepage_products {
		products_id {
			id
			title
			price
			main_image {
				id
			}
		}
	}
	homepage_banners {
		title
		image {
			id
		}
		collection {
			id
			title
		}
		category {
			id
			title
		}
	}
}
