query Products(
	$limit: Int
	$sort: [String]
	$page: Int
	$filter: products_filter
) {
	products(filter: $filter, sort: $sort, limit: $limit, page: $page) {
		id
		title
		price
		main_image {
			id
		}
	}
}

query GetProductsByIds($ids: [String]) {
	products(filter: {id: {_in: $ids}}) {
		id
		main_image {
			id
		}
		title
		price
		product_variants {
			id
			color_id {
				title
			}
			size_id {
				small_title
			}
			qunatity
		}
	}
}

query GetCartProductsByIds(
	$ids: [String]
	$pvi: String
	$quantity: GraphQLStringOrFloat
) {
	products(
		filter: {
			id: {_in: $ids}
			product_variants: {id: {_eq: $pvi}, qunatity: {_gte: $quantity}}
		}
	) {
		id
		main_image {
			id
		}
		title
		price
		product_variants {
			id
			color_id {
				title
			}
			size_id {
				small_title
			}
			qunatity
		}
	}
}
