query Products(
	$limit: Int
	$sort: [String]
	$page: Int
	$filter: products_filter
) {
	products(filter: $filter, sort: $sort, limit: $limit, page: $page) {
		id
		title
		price
		main_image {
			id
		}
	}
}

query GetProductsByIds($ids: [String]) {
	products(filter: {id: {_in: $ids}}) {
		id
		main_image {
			id
		}
		title
		price
		product_variants {
			id
			color_id {
				title
			}
			size_id {
				small_title
			}
			qunatity
		}
	}
}

query GetCartProductsByIds($ids: [String], $variant_ids: [String]) {
	products(filter: {id: {_in: $ids}}) {
		id
		main_image {
			id
		}
		title
		price
		product_variants(filter: {id: {_in: $variant_ids}}) {
			id
			color_id {
				title
			}
			size_id {
				small_title
			}
			qunatity
		}
	}
}
